/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FaceUiModule extends AbstractFaceUiModule {

	public FaceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
