/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face.scoping;

import com.epistimist.face.scoping.AbstractFaceScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class FaceScopeProvider extends AbstractFaceScopeProvider {

}
