/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face;

import com.epistimist.face.FaceStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FaceStandaloneSetup extends FaceStandaloneSetupGenerated {

	public static void doSetup() {
		new FaceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
