/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.face;

import com.epistimis.face.AbstractFaceRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FaceRuntimeModule extends AbstractFaceRuntimeModule {
}
